### ISSUE TITLE
AWS signature canonical string and query not urlencoded.

### ISSUE THREAD

**Issue by pghole** [andrewjroth/requests-auth-aws-sigv4#6]
Hey,

I am forming the Authorisation header and I am not using the Boto libraries. While forming the canonical uri and canonical querystring the aws documentation(https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html ) says that we need to urlencode them. However, i do not see any urlencoding in the __init__.py file. Can you pls. check if that's missing or there is some gap in my understanding ? This is with reference to the s3

**Comment by andrewjroth** [comment]
Hello,

Because this implementation is specific for the [requests](https://docs.python-requests.org/en/master/) package, the query string is assumed to be already urlencoded.  The `qs` variable comes from the `urlparse` of `r.url`, which itself is a `requests.models.PreparedRequest` object (see code for [requests_auth_aws_sigv4/__init__.py line 109](https://github.com/andrewjroth/requests-auth-aws-sigv4/blob/5bdea4e0ad83689258b8916819dd170aa7348005/requests_auth_aws_sigv4/__init__.py#L109)).

It's possible this assumption is incorrect, so if you are seeing a problem or errors, please let me know what you did for me to recreate it.

Thanks!

**Comment by pghole** [comment]
Thanks @andrewjroth for the answer. Got it.

However, I think there can be some issue since ```requests``` uses ```quote_plus``` and aws needs the encoding in format as space = %20 (```quote```) and not + . I am trying to pass the params in the url itself then, rather than passing it as params dictionary as below, to get the %20 encoding.

for eg --> requests.get("http://abc.com/xyz?uploadid=13xxsfw&partnumber=2) # rather than passing params={params_dict}

Also, can you pls. help me with the understanding of ```Canonical URI``` in https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html as it says for s3 we should not double encode it. Isn't the requests module already encoding it or it is expected that we encode it once more, since I now pass the entire thing as uri. What is expected here which is different for s3 than other services ?

**Comment by andrewjroth** [comment]
Do you have an example failure case?  Do you have sample code which fails?  I see what you are saying, but I am not sure how to test it.  It's possible the handling of parameters and encoding could be improved.

**Comment by andrewjroth** [comment]
I believe this may be addressed by #9
